name: pcuser
description: "A new Flutter project."
publish_to: "none" 

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Core packages
  intl: ^0.18.1
  http: ^1.5.0
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.3.3
  permission_handler: ^12.0.1

  # Firebase
  firebase_core: ^3.13.1
  cloud_firestore: ^5.6.8
  firebase_auth: ^5.5.4

  # State management
  provider: ^6.1.5

  # Maps & location
  google_maps_flutter: ^2.12.3
  geocoding: ^3.0.0
  geolocator: ^14.0.2

  # Notifications
  flutter_local_notifications: ^17.2.0

  # Payment
  razorpay_flutter: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
